### ISSUE TITLE
Some data errors

### ISSUE THREAD

**Issue by renewooller** [billy1380/JavaEPFImporter#7]
Hi. Thanks for writing this tool - I couldn't get the python one working, so it's really appreciated. 

I'm seeing these data issues. Is anyone else? Any tips on how to overcome them?

Thanks in advance. 
```
2017-09-27 01:44:27,245 INFO  MySqlIngester - Beginning full ingest of epf_paid_application_popularity_per_genre (3169192 records)
2017-09-27 01:46:27,251 INFO  MySqlIngester - ...at record 923600...
2017-09-27 01:48:27,263 INFO  MySqlIngester - ...at record 1844200...
2017-09-27 01:50:27,266 INFO  MySqlIngester - ...at record 2766400...
2017-09-27 01:51:19,345 ERROR Program - An error occured while ingesting data.
java.util.IllegalFormatConversionException: d != java.lang.String

2017-09-27 01:51:19,347 WARN  Program - The following files encountered errors and were not imported:
        itunes/popularity20170913/[album_popularity_per_genre, paid_ipad_application_popularity_per_genre, free_ipad_application_popularity_per_genre, song_popularity_per_genre, free_application_popularity_per_genre, paid_application_popularity_per_genre]
```
and

```
ÏÎ·ÏÎµÏÎ¯Î± i-Status ÎµÎ¯Î½Î±Î¹ ÏÏÏÎ¯Ï ÎµÏÎ¹ÏÎ»Î­Î¿Î½ ÏÏÎ­ÏÏÎ· ÎºÎ±Î¹ Î¼ÏÎ¿ÏÎµÎ¯ Î½Î± ÎµÎ½ÎµÏÎ³Î¿ÏÎ¿Î¹Î·Î¸ÎµÎ¯ Î³Î¹Î± Ï
                                                                                                                       Î¹Ï online ÎµÎ³ÎºÎ±Ï
                                                                                                                                           Î±ÏÏ
                                                                                                                                               Î¬ÏÎµÎ¹Ï Ï
                                                                                                                                                         ÏÎ½ ÎµÏÎ±ÏÎ¼Î¿Î³ÏÎ½ Status Î¼Îµ Ï
          ÎºÎ±Î¹ username.', 'New stuff!!', NULL, 'http://www.mainsys.gr', 'http://is3.mzstatic.com/image/thumb/Purple1/v4/a8/f5/26/a8f526ab-d2bc-4a07-cad0-89017fd613b6/source/320x480bb.jpg', NULL, NULL, NULL, '320x480', NULL, NULL, NULL, 'http://is1.mzstatic.com/image/thumb/Purple3/v4/e2/e0/9b/e2e09b60-642a-980f-837f-240c7ec108ae/source/360x480bb.jpg', NULL, NULL, NULL, '360x480', NULL, NULL, NULL)
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xE2?\xA2 In...' for column 'title' at row 18
 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4206)
 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4140)
 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2597)
```

**Comment by billy1380** [comment]
Hi @renewooller, this might not be an issue with the tool... it might be an issue with the encoding on the mysql server. Do you have utf8mb4 encoding enabled?

**Comment by renewooller** [comment]
Thanks - I'll try mb4

**Comment by renewooller** [comment]
I have tried setting the charset and collation for the db like so:

```
ALTER DATABASE epf CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

and

```
ALTER DATABASE epf CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
```

Running the importer just on the 'song' table gets the problem immediately. The song table does not exist yet - so no need to alter the encoding for it.

This is the command I'm using:
```
docker run --rm -it -v "$PWD:/app" -v "$PWD/../itunes:/app/itunes" -w /app openjdk:7-jre-alpine java -Xmx1024m -jar ./target/epfimporter-0.0.1-SNAPSHOT-jar-with-dependencies.jar -d <redacted> -u admin -p <redacted> -n epf -w '^song$' itunes/itunes20170913
```

I've had similar problems in other projects before when trying to support emojis - I recall the encoding on the JDBC driver needing to be set. Let me know if you can replicate the problem.

FYI to build the jar I'm using:
```
git clone https://github.com/billy1380/JavaEPFImporter.git;
cd JavaEPFImporter;
docker run -it --rm --name my-maven-project -v "$PWD":/usr/src/mymaven -w /usr/src/mymaven maven:3.2-jdk-7 mvn package;
```

**Comment by renewooller** [comment]
I think this may be the problem:

show variables like 'character_set_server';
> character_set_server	latin1

**Comment by renewooller** [comment]
This is working now, as it it's not crashing. However, the © symbol in 'copyright' column is showing up as â, and various artist names also have incorrect encodings, eg "Wiener Philharmoniker & Karl BÃ¶hm" or "Augustin Dumay & Maria JoÃ£o Pires"

Looking at song 960799112 for example, comes out as: SkÃ¥l in the database, but when grepping from the original file, it's Skål.

I don't want to come across as hassling you to fix this, but I'm really interested if you can replicate the problem.

**Comment by renewooller** [comment]
I think the line in Connection.java
```
 executeQuery("set names \'utf8\'");
```
should be:
```
executeQuery("set names \'utf8mb4\'");
```
Will test and let you know.

**Comment by billy1380** [comment]
I think that will work, it certainly rings a bell... I think I have made that change somewhere. When you are happy with the results, please do a pull request and I will merge it straight away.

Thanks for going through it.

**Comment by renewooller** [comment]
According to these:
http://info.michael-simons.eu/2013/01/21/java-mysql-and-multi-byte-utf-8-support/
https://mathiasbynens.be/notes/mysql-utf8mb4

having "set names utf8mb4" should have solved it but it doesn't seem to. I've also tried useUnicode=true and characterEncoding=utf-8 and changing all the relevant variables on the server. Nothing seems to be able to get around the problem. 

It could be that there are some characters that aren't valid utf8mb4 in the files, and so it's defaulting to a more lenient encoding. 

Eg when I try:
mysql --local-infile -h 127.0.0.1 -u <redacted>-p<redacted> epf \
> -e "LOAD DATA LOCAL INFILE './itunes/itunes20170913/artist' \
> INTO TABLE artist CHARACTER SET utf8mb4 \
> FIELDS TERMINATED BY X'01' \
> LINES TERMINATED BY '\n' \
> IGNORE 34 LINES"
ERROR 1300 (HY000) at line 1: Invalid utf8mb4 character string: '张雨生'

**Comment by renewooller** [comment]
Looking into this further it appears that this character is a 6-byte utf8 character: http://graphemica.com/%E5%BC%A0
Mysql only supports up to 4 byte. So I don't think there's any way of dealing with this one.

**Comment by billy1380** [comment]
Only looks like 3 bytes to me 0xE5 0xBC 0xA0 (e5bca0)

**Comment by renewooller** [comment]
I have this working now: 
```
mysql --local-infile -h 127.0.0.1 -u <> -p<> epf \
-e "LOAD DATA LOCAL INFILE './itunes/test/itunes20170913/artist' \
INTO TABLE artist CHARACTER SET utf8mb4 \
FIELDS TERMINATED BY X'01' ESCAPED BY '' \
LINES TERMINATED BY X'020A' \
IGNORE 34 LINES"
```
The important part being  " escaped by '' " , which overrides the default '\'

I wonder if the same issue is behind the fallback to latin-1 in the java importer?

**Comment by renewooller** [comment]
yah, I got the nybble confused with the byte, silly me.

**Comment by billy1380** [comment]
I am trying to think if anything has changed... I tested with data in the `smalldata` folder (which contains some kangi) do you mind doing me a favour and checking that e.g. https://github.com/billy1380/JavaEPFImporter/blob/master/smalldata/application_detail
imports for you with no trouble.
